tradingradar/config/routes.rb
Rails.application.routes.draw do
  get 'message/emailreset'
  root "home#index", as: "home"

  get "press_release/source0" #testing source
  get "press_release/source1"
  get "press_release/source2"
  get "press_release/source3"
  get "press_release/source4"
  get "press_release/source5"
  get "press_release/source6"
  get "press_release/source7"
  get "press_release/source8"
  get "press_release/source9"
  get "press_release/source10"
  get "press_release/source11"
  get "press_release/source12"
  get "press_release/source13"
  get "press_release/source14"
  get "press_release/source15"
  get "press_release/source16"
  get "press_release/source16"
  get "press_release/source17"
  get "press_release/source18"
  get "press_release/source19"

  #get 'stock/:id' => 'stock#press_release' #good for: http://www.localhost:3000/stock/a2a/
  get "stock/:id" => "stock#index"  # Goes to --> http://localhost:3000/stock/a2a/?isin=IT0001233417

  get "market/italy"
  get "market/italy" => "market#italy"

  get "market/france"
  get "market/france" => "market#france"

  get "pages/contacts"
  post "contacts" => "pages#contacts"
  get "contacts" => "pages#contacts"

  get "pages/about"
  get "about" => "pages#about"

  post "send" => "pages#send"

  get "search/search"
  get "search" => "search#search"

  #devise_for :followers

  get "home/index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "signup" => "users#new"

  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"

  scope "(:locale)" do
    resources :market_suggestions_newsletters
    resources :analyses
    resources :follow_stock_newsletters
    resources :items
    resources :dax30_reports
    resources :users
    resources :markets
    resources :user_reports
    resources :cac40_reports
    resources :fias_reports
    resources :sources
    resources :stocks
    resources :users
    resources :source_frances
    resources :source_italies
    root "home#index", as: "home-locale", via: :all

    get "pages/contacts"
    get "pages/about"
    get "pages/privacy-policy"
  end

  devise_for :followers, :controllers => {:omniauth_callbacks => "followers/omniauth_callbacks"}
end

tradingradar/app/models/source_italy.rb
class SourceItaly < ApplicationRecord
end

tradingradar/app/controllers/source_italies_controller.rb
class SourceItaliesController < ApplicationController
  before_action :set_source_italy, only: [:show, :edit, :update, :destroy]

  # GET /source_italies
  # GET /source_italies.json
  def index
    @source_italies = SourceItaly.all
  end

  # GET /source_italies/1
  # GET /source_italies/1.json
  def show
  end

  # GET /source_italies/new
  def new
    @source_italy = SourceItaly.new
  end

  # GET /source_italies/1/edit
  def edit
  end

  # POST /source_italies
  # POST /source_italies.json
  def create
    @source_italy = SourceItaly.new(source_italy_params)

    respond_to do |format|
      if @source_italy.save
        format.html { redirect_to @source_italy, notice: "Source italy was successfully created." }
        format.json { render :show, status: :created, location: @source_italy }
      else
        format.html { render :new }
        format.json { render json: @source_italy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /source_italies/1
  # PATCH/PUT /source_italies/1.json
  def update
    respond_to do |format|
      if @source_italy.update(source_italy_params)
        format.html { redirect_to @source_italy, notice: "Source italy was successfully updated." }
        format.json { render :show, status: :ok, location: @source_italy }
      else
        format.html { render :edit }
        format.json { render json: @source_italy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /source_italies/1
  # DELETE /source_italies/1.json
  def destroy
    @source_italy.destroy
    respond_to do |format|
      format.html { redirect_to source_italies_url, notice: "Source italy was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_source_italy
    @source_italy = SourceItaly.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def source_italy_params
    params.require(:source_italy).permit(:isin, :name, :url_0, :url_1, :url_2, :url_3, :url_4, :url_5, :url_6, :url_7, :url_8, :url_9, :url_10, :url_11)
  end
end

tradingradar/app/helpers/source_italies_helper.rb
module SourceItaliesHelper
end

tradingradar/app/views/source_italies/_form.html.erb
<%= form_with(model: source_italy, local: true) do |form| %>
  <% if source_italy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(source_italy.errors.count, "error") %> prohibited this source_italy from being saved:</h2>

      <ul>
      <% source_italy.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :isin %>
    <%= form.text_field :isin %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :url_0 %>
    <%= form.text_field :url_0 %>
  </div>

  <div class="field">
    <%= form.label :url_1 %>
    <%= form.text_field :url_1 %>
  </div>

  <div class="field">
    <%= form.label :url_2 %>
    <%= form.text_field :url_2 %>
  </div>

  <div class="field">
    <%= form.label :url_3 %>
    <%= form.text_field :url_3 %>
  </div>

  <div class="field">
    <%= form.label :url_4 %>
    <%= form.text_field :url_4 %>
  </div>

  <div class="field">
    <%= form.label :url_5 %>
    <%= form.text_field :url_5 %>
  </div>

  <div class="field">
    <%= form.label :url_6 %>
    <%= form.text_field :url_6 %>
  </div>

  <div class="field">
    <%= form.label :url_7 %>
    <%= form.text_field :url_7 %>
  </div>

  <div class="field">
    <%= form.label :url_8 %>
    <%= form.text_field :url_8 %>
  </div>

  <div class="field">
    <%= form.label :url_9 %>
    <%= form.text_field :url_9 %>
  </div>

  <div class="field">
    <%= form.label :url_10 %>
    <%= form.text_field :url_10 %>
  </div>

  <div class="field">
    <%= form.label :url_11 %>
    <%= form.text_field :url_11 %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

tradingradar/app/views/source_italies/edit.html.erb
<%= render("./partials/header/header") %>
<!--The main content-->
<div class="shell">
  <h1>Editing Source Italy</h1>
  <%= render 'form', source_italy: @source_italy %>
  <%= link_to 'Show', @source_italy %> |
  <%= link_to 'Back', source_italies_path %>
</div>

tradingradar/app/views/source_italies/index.html.erb
<%= render("./partials/header/header") %>
<!--The main content-->
<div class="shell">
  <p id="notice"><%= notice %></p>
  <h1>Source Italies</h1>
  <div class="table-wrapper">
    <table class="table table-hover table-sm">
    <thead>
      <tr>
        <th scope="col">Isin</th>
        <th scope="col">Name</th>
        <th scope="col">Url 0</th>
        <th scope="col">Url 1</th>
        <th scope="col">Url 2</th>
        <th scope="col">Url 3</th>
        <th scope="col">Url 4</th>
        <th scope="col">Url 5</th>
        <th scope="col">Url 6</th>
        <th scope="col">Url 7</th>
        <th scope="col">Url 8</th>
        <th scope="col">Url 9</th>
        <th scope="col">Url 10</th>
        <th scope="col">Url 11</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @source_italies.each do |source_italy| %>
        <tr class='<%= cycle('odd', 'even') %>'>
          <td title="<%= source_italy.isin %>"><%= source_italy.isin %></td>
          <td title="<%= source_italy.name %>"><%= source_italy.name %></td>
          <td title="<%= source_italy.url_0 %>"><%= source_italy.url_0 %></td>
          <td title="<%= source_italy.url_1 %>"><%= source_italy.url_1 %></td>
          <td title="<%= source_italy.url_2 %>"><%= source_italy.url_2 %></td>
          <td title="<%= source_italy.url_3 %>"><%= source_italy.url_3 %></td>
          <td title="<%= source_italy.url_4 %>"><%= source_italy.url_4 %></td>
          <td title="<%= source_italy.url_5 %>"><%= source_italy.url_5 %></td>
          <td title="<%= source_italy.url_6 %>"><%= source_italy.url_6 %></td>
          <td title="<%= source_italy.url_7 %>"><%= source_italy.url_7 %></td>
          <td title="<%= source_italy.url_8 %>"><%= source_italy.url_8 %></td>
          <td title="<%= source_italy.url_9 %>"><%= source_italy.url_9 %></td>
          <td title="<%= source_italy.url_10 %>"><%= source_italy.url_10 %></td>
          <td title="<%= source_italy.url_11 %>"><%= source_italy.url_11 %></td>
          <td><%= link_to 'Show', source_italy %></td>
          <td><%= link_to 'Edit', edit_source_italy_path(source_italy) %></td>
          <td><%= link_to 'Destroy', source_italy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  </div>
  <br>
  <%= link_to 'New Source Italy', new_source_italy_path %>
</div>

tradingradar/app/views/source_italies/new.html.erb
<%= render("./partials/header/header") %>
<!--The main content-->
<div class="shell">
  <h1>New Source Italy</h1>
  <%= render 'form', source_italy: @source_italy %>
  <%= link_to 'Back', source_italies_path %>
</div>

tradingradar/app/views/source_italies/show.html.erb
<%= render("./partials/header/header") %>
<!--The main content-->
<div class="shell">
  <p id="notice"><%= notice %></p>
  <p>
    <strong>Isin:</strong>
    <%= @source_italy.isin %>
  </p>
  <p>
    <strong>Name:</strong>
    <%= @source_italy.name %>
  </p>
  <p>
    <strong>Url 0:</strong>
    <%= @source_italy.url_0 %>
  </p>
  <p>
    <strong>Url 1:</strong>
    <%= @source_italy.url_1 %>
  </p>
  <p>
    <strong>Url 2:</strong>
    <%= @source_italy.url_2 %>
  </p>
  <p>
    <strong>Url 3:</strong>
    <%= @source_italy.url_3 %>
  </p>
  <p>
    <strong>Url 4:</strong>
    <%= @source_italy.url_4 %>
  </p>
  <p>
    <strong>Url 5:</strong>
    <%= @source_italy.url_5 %>
  </p>
  <p>
    <strong>Url 6:</strong>
    <%= @source_italy.url_6 %>
  </p>
  <p>
    <strong>Url 7:</strong>
    <%= @source_italy.url_7 %>
  </p>
  <p>
    <strong>Url 8:</strong>
    <%= @source_italy.url_8 %>
  </p>
  <p>
    <strong>Url 9:</strong>
    <%= @source_italy.url_9 %>
  </p>
  <p>
    <strong>Url 10:</strong>
    <%= @source_italy.url_10 %>
  </p>
  <p>
    <strong>Url 11:</strong>
    <%= @source_italy.url_11 %>
  </p>
  <%= link_to 'Edit', edit_source_italy_path(@source_italy) %> |
  <%= link_to 'Back', source_italies_path %>
</div>