tradingradar/config/routes.rb
Rails.application.routes.draw do
  get 'message/emailreset'
  root "home#index", as: "home"

  get "press_release/source0" #testing source
  get "press_release/source1"
  get "press_release/source2"
  get "press_release/source3"
  get "press_release/source4"
  get "press_release/source5"
  get "press_release/source6"
  get "press_release/source7"
  get "press_release/source8"
  get "press_release/source9"
  get "press_release/source10"
  get "press_release/source11"
  get "press_release/source12"
  get "press_release/source13"
  get "press_release/source14"
  get "press_release/source15"
  get "press_release/source16"
  get "press_release/source16"
  get "press_release/source17"
  get "press_release/source18"
  get "press_release/source19"

  #get 'stock/:id' => 'stock#press_release' #good for: http://www.localhost:3000/stock/a2a/
  get "stock/:id" => "stock#index"  # Goes to --> http://localhost:3000/stock/a2a/?isin=IT0001233417

  get "market/italy"
  get "market/italy" => "market#italy"

  get "market/france"
  get "market/france" => "market#france"

  get "pages/contacts"
  post "contacts" => "pages#contacts"
  get "contacts" => "pages#contacts"

  get "pages/about"
  get "about" => "pages#about"

  post "send" => "pages#send"

  get "search/search"
  get "search" => "search#search"

  #devise_for :followers

  get "home/index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "signup" => "users#new"

  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"

  scope "(:locale)" do
    resources :market_suggestions_newsletters
    resources :analyses
    resources :follow_stock_newsletters
    resources :items
    resources :dax30_reports
    resources :users
    resources :markets
    resources :user_reports
    resources :cac40_reports
    resources :fias_reports
    resources :sources
    resources :stocks
    resources :users
    resources :source_frances
    resources :source_italies
    root "home#index", as: "home-locale", via: :all

    get "pages/contacts"
    get "pages/about"
    get "pages/privacy-policy"
  end

  devise_for :followers, :controllers => {:omniauth_callbacks => "followers/omniauth_callbacks"}
end

tradingradar/app/models/stock.rb
class Stock < ApplicationRecord 
    
  validates :isin, presence: true, uniqueness: true
  validates :reuters, uniqueness: true
  validates :last_price, numericality: {greater_than_or_equal_to: 0.00}, allow_nil: true
  
end

tradingradar/app/controllers/stock_controller.rb
class StockController < ApplicationController
  def index
    @isin = params[:isin] ? params[:isin] : nil

    #TODO: if not ISIN???

    if @isin
      @stock = Stock.find_by isin: @isin

      if @stock
        @reuters = @stock.reuters
        marketCode = @stock.market

        case marketCode
        when "IT"
          @market = "italy"
          @urls = SourceItaly.find_by isin: @isin
          @reports = FiasReport.find_by isin: @isin

          @stockMediaData = {
            "urlCompanyProfile" => @urls.url_0,
            "urlCompanyInfos" => @urls.url_1,
            "sourceCompanyInfos" => "Borsa Italiana",
            "breadcrumbLink" => "markets.italy",
            "media" => [
              {
                "id" => "source1",
                "class" => "borsaitaliana",
                "iso" => "it",
                "name" => "Borsa Italiana",
                "logo" => "logo/media/borsaItalianaLogo.png",
                "url" => @urls.url_0,
                "rootUrl" => "https://www.borsaitaliana.it",
                "data" => [
                  {
                    "label" => t("layouts.application.support"),
                    "value" => @reports.borsaitaliana_support,
                  },
                  {
                    "label" => t("layouts.application.resistance"),
                    "value" => @reports.borsaitaliana_resistance,
                  },
                  {
                    "label" => t("layouts.application.fta"),
                    "value" => @reports.borsaitaliana_fta,
                  },
                  {
                    "label" => t("layouts.application.rsi"),
                    "value" => @reports.borsaitaliana_rsi,
                  },
                  {
                    "label" => t("layouts.application.volatility"),
                    "value" => @reports.borsaitaliana_volatility,
                  },
                ],
              },
              {
                "id" => "source2",
                "name" => "Il Sole 24 Ore",
                "class" => "ilsole24ore",
                "iso" => "it",
                "logo" => "logo/media/ilSole24OreLogo.png",
                "url" => "https://www.ilsole24ore.com",
                "rootUrl" => "https://www.ilsole24ore.com",
                "data" => [

                  {
                    "label" => t("layouts.application.rating"),
                    "value" => @reports.sole24ore_rating,
                  },
                  {
                    "label" => t("layouts.application.relativeStrenght"),
                    "value" => @reports.sole24ore_relativestrenght,
                  },
                  {
                    "label" => t("layouts.application.shortTrend"),
                    "value" => @reports.sole24ore_shorttrend,
                  },
                  {
                    "label" => t("layouts.application.mediumTrend"),
                    "value" => @reports.sole24ore_mediumtrend,
                  },

                ],
              },
              {
                "id" => "source3",
                "class" => "milanofinanza",
                "iso" => "it",
                "name" => "Milano Finanza",
                "logo" => "logo/media/milanofinanza.png",
                "url" => @urls.url_5,
                "rootUrl" => "https://www.milanofinanza.it",
                "data" => [
                  {
                    "label" => t("layouts.application.risk"),
                    "value" => @reports.milanofinanza_risk,
                  },
                  {
                    "label" => t("layouts.application.rating"),
                    "value" => @reports.milanofinanza_rating,
                  },
                  {
                    "label" => t("layouts.application.shortTrend"),
                    "value" => @reports.milanofinanza_trendshort,
                  },
                  {
                    "label" => t("layouts.application.mediumTrend"),
                    "value" => @reports.milanofinanza_trendmedium,
                  },
                  {
                    "label" => t("layouts.application.longTrend"),
                    "value" => @reports.milanofinanza_trendlong,
                  },
                ],
              },
              {
                "id" => "source4",
                "name" => "Teleborsa",
                "class" => "teleborsa",
                "iso" => "it",
                "logo" => "logo/media/teleBorsa.png",
                "url" => @urls.url_6,
                "rootUrl" => "https://www.teleborsa.it",
                "data" => [
                  {
                    "label" => t("layouts.application.support"),
                    "value" => @reports.teleborsa_support,
                  },
                  {
                    "label" => t("layouts.application.resistance"),
                    "value" => @reports.teleborsa_resistance,
                  },
                ],
              },
            ],
          }
        when "FR"
          @market = "france"
          @urls = SourceFrance.find_by isin: @isin
          @reports = Cac40Report.find_by isin: @isin

          @stockMediaData = {
            "urlCompanyProfile" => @urls.url_0,
            "urlCompanyInfos" => @urls.url_1,
            "sourceCompanyInfos" => "TradingSat",
            "breadcrumbLink" => "markets.france",
            "media" => [
              {
                "id" => "source5",
                "class" => "tradingsat",
                "iso" => "fr",
                "name" => "TradingSat",
                "logo" => "logo/media/tradingSat.png",
                "url" => @urls.url_1,
                "rootUrl" => "https://www.tradingsat.com",
                "data" => [
                  {
                    "label" => t("layouts.application.shortTrend"),
                    "value" => @reports.tradingsat_trendshort,
                  },
                  {
                    "label" => t("layouts.application.mediumTrend"),
                    "value" => @reports.tradingsat_trendmedium,
                  },
                  {
                    "label" => t("layouts.application.longTrend"),
                    "value" => @reports.tradingsat_trendlong,
                  },
                ],
              },

              {
                "id" => "source6",
                "class" => "boursefortuneo",
                "iso" => "fr",
                "name" => "Bourse Fortuneo",
                "logo" => "logo/media/bourseFortuneo.png",
                "url" => "https://bourse.fortuneo.fr",
                "rootUrl" => "https://bourse.fortuneo.fr",
                "data" => [
                  {
                    "label" => t("layouts.application.support"),
                    "value" => @reports.boursefortuneo_support,
                  },
                  {
                    "label" => t("layouts.application.resistance"),
                    "value" => @reports.boursefortuneo_resistance,
                  },
                  {
                    "label" => t("layouts.application.target"),
                    "value" => @reports.boursefortuneo_target,
                  },
                  {
                    "label" => t("layouts.application.rating"),
                    "value" => @reports.boursefortuneo_rating,
                  },
                  {
                    "label" => t("layouts.application.shortTrend"),
                    "value" => @reports.boursefortuneo_trendshort,
                  },
                  {
                    "label" => t("layouts.application.mediumTrend"),
                    "value" => @reports.boursefortuneo_trendmedium,
                  },
                ],
              },

              {
                "id" => "source7",
                "class" => "lefigaro",
                "iso" => "fr",
                "name" => "Le Figaro",
                "logo" => "logo/media/leFigaro.png",
                "url" => @urls.url_4,
                "rootUrl" => "http://bourse.lefigaro.fr",
                "data" => [
                  {
                    "label" => t("layouts.application.consensus"),
                    "value" => @reports.lefigaro_consensus,
                  },
                ],
              },

            ],
          }
        else
          #nothing
        end
      end
    end
  end
end

tradingradar/app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :set_stock, only: [:show, :edit, :update, :destroy]
  #before_action :require_user, only: [:index, :show]

  # GET /stocks
  # GET /stocks.json
  def index
    @stocks = Stock.all
  end

  # GET /stocks/1
  # GET /stocks/1.json
  def show
  end

  # GET /stocks/new
  def new
    @stock = Stock.new
  end

  # GET /stocks/1/edit
  def edit
  end

  # POST /stocks
  # POST /stocks.json
  def create
    @stock = Stock.new(stock_params)

    respond_to do |format|
      if @stock.save
        format.html { redirect_to @stock, notice: "Stock was successfully created." }
        format.json { render :show, status: :created, location: @stock }
      else
        format.html { render :new }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stocks/1
  # PATCH/PUT /stocks/1.json
  def update
    respond_to do |format|
      if @stock.update(stock_params)
        format.html { redirect_to @stock, notice: "Stock was successfully updated." }
        format.json { render :show, status: :ok, location: @stock }
      else
        format.html { render :edit }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stocks/1
  # DELETE /stocks/1.json
  def destroy
    @stock.destroy
    respond_to do |format|
      format.html { redirect_to stocks_url, notice: "Stock was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_stock
    @stock = Stock.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def stock_params
    params.require(:stock).permit(:isin, :reuters, :name, :sector, :last_price, :variation, :market_phase, :corporate_url, :address, :phone, :market, :currency, :profile, :keywords, :dividend, :dividend_date, :code, :dividend_yeld, :performance1, :performance6, :performance12, stock_ids: [])
  end
end

tradingradar/app/helpers/stock_helper.rb
module StockHelper
end

tradingradar/app/helpers/stocks_helper.rb
module StocksHelper
end

tradingradar/app/views/stocks/_form.html.erb
<%= form_with(model: stock, local: true) do |form| %>
  <% if stock.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(stock.errors.count, "error") %> prohibited this stock from being saved:</h2>
      <ul>
        <% stock.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= form.label :isin %>
    <%= form.text_field :isin, class:'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :reuters %>
    <%= form.text_field :reuters, class:'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class:'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :sector %>
    <%= form.text_field :sector, class:'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :last_price %>
    <%= form.text_field :last_price, class:'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :variation %>
    <%= form.text_field :variation, class:'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :market_phase %>
    <%= form.text_field :market_phase, class:'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :corporate_url %>
    <%= form.text_field :corporate_url, class:'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :address %>
    <%= form.text_field :address, class:'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :phone %>
    <%= form.text_field :phone, class:'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :market %>
    <%= form.text_field :market, class:'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :currency %>
    <%= form.text_field :currency, class:'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :profile %>
    <%= form.text_area :profile, class:'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :keywords %>
    <%= form.text_field :keywords, class:'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :dividend %>
    <%= form.text_field :dividend, class:'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :dividend_date %>
    <%= form.text_field :dividend_date, class:'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :dividend_yeld %>
    <%= form.text_field :dividend_yeld, class:'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :performance1 %>
    <%= form.text_field :performance1, class:'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :performance6 %>
    <%= form.text_field :performance6, class:'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :performance12 %>
    <%= form.text_field :performance12, class:'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :code %>
    <%= form.text_field :code, class:'form-control' %>
  </div>
  <!--<div class="form-group">
  	<% form.label :sources %>
	<% for source in Source.all %>
	  <% check_box_tag "stock[source_ids][]", source.id %>
	  <% source.name %> - <% source.isin %><br />
	<% end %>
  </div>  -->
  <div class="actions">
    <%= form.submit nil, class: 'btn btn-primary' %>
  </div>
<% end %>

tradingradar/app/views/stocks/edit.html.erb
<%= render("./partials/header/header") %>
<!--The main content-->
<div class="shell">
  <h1>Editing Stock</h1>
  <%= render 'form', stock: @stock %>
  <%= link_to 'Show', @stock %> |
  <%= link_to 'Back', stocks_path %>
</div>

tradingradar/app/views/stocks/index.html.erb
  <%= render("./partials/header/header") %>
  <!--The main content-->
  <div class="shell">
    <p id="notice"><%= notice %></p>
    <h1>Stocks</h1>
    <div class="table-wrapper">
      <table class="table table-hover table-sm">
        <thead>
          <tr>
            <th scope="col">Isin</th>
            <th scope="col">Reuters</th>
            <th scope="col">Name</th>
            <th scope="col">Sector</th>
            <th scope="col">Last price</th>
            <th scope="col">Variation</th>
            <th scope="col">Market phase</th>
            <th scope="col">Corporate url</th>
            <th scope="col">Address</th>
            <th scope="col">Phone</th> 
            <th scope="col">Market</th>
            <th scope="col">Currency</th>
            <th scope="col">Profile</th>
            <th scope="col">Keywords</th>
            <th scope="col">Dividend</th>
            <th scope="col">Dividend date</th>
            <th scope="col">Dividend yeld</th>
            <th scope="col">Performance1</th>
            <th scope="col">Performance6</th>
            <th scope="col">Performance12</th>
            <th scope="col">Code</th>
            <th scope="col" colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @stocks.each do |stock| %>
            <tr class='<%= cycle('odd', 'even') %>'>
              <td title="<%= stock.isin %>"><%= stock.isin %></td>
              <td title="<%= stock.reuters %>"><%= stock.reuters %></td>
              <td title="<%= stock.name %>"><%= stock.name %></td>
              <td title="<%= stock.sector %>"><%= stock.sector %></td>
              <td title="<%= stock.last_price %>"><%= stock.last_price %></td>
              <td title="<%= stock.variation %>"><%= stock.variation %></td>
              <td title="<%= stock.market_phase %>"><%= stock.market_phase %></td>
              <td title="<%= stock.corporate_url %>"><%= stock.corporate_url %></td>
              <td title="<%= stock.address %>"><%= stock.address %></td>
              <td title="<%= stock.phone %>"><%= stock.phone %></td>
              <td title="<%= stock.market %>"><%= stock.market %></td>
              <td title="<%= stock.currency %>"><%= stock.currency %></td>
              <td title="<%= stock.profile %>"><%= stock.profile %></td>
              <td title="<%= stock.keywords %>"><%= stock.keywords %></td>
              <td title="<%= stock.dividend %>"><%= stock.dividend %></td>
              <td title="<%= stock.dividend_date %>"><%= stock.dividend_date %></td>
              <td title="<%= stock.dividend_yeld %>"><%= stock.dividend_yeld %></td>
              <td title="<%= stock.performance1 %>"><%= stock.performance1 %></td>
              <td title="<%= stock.performance6 %>"><%= stock.performance6 %></td>
              <td title="<%= stock.performance12 %>"><%= stock.performance12 %></td>
              <td title="<%= stock.code %>"><%= stock.code %></td>
              <td><%= link_to 'Show', stock %></td>
              <td><%= link_to 'Edit', edit_stock_path(stock) %></td>
              <td><%= link_to 'Destroy', stock, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <br>
    <%= link_to 'New Stock', new_stock_path %>
  </div>

tradingradar/app/views/stocks/new.html.erb
<%= render("./partials/header/header") %>
<!--The main content-->
<div class="shell">
  <h1>New Stock</h1>
  <%= render 'form', stock: @stock %>
  <%= link_to 'Back', stocks_path %>
</div>

tradingradar/app/views/stocks/show.html.erb
<%= render("./partials/header/header") %>
<!--The main content-->
<div class="shell">
  <p id="notice"><%= notice %></p>
  <p>
    <strong>Isin:</strong>
    <%= @stock.isin %>
  </p>
  <p>
    <strong>Reuters:</strong>
    <%= @stock.reuters %>
  </p>
  <p>
    <strong>Name:</strong>
    <%= @stock.name %>
  </p>
  <p>
    <strong>Sector:</strong>
    <%= @stock.sector %>
  </p>
  <p>
    <strong>Last price:</strong>
    <%= @stock.last_price %>
  </p>
  <p>
    <strong>Variation:</strong>
    <%= @stock.variation %>
  </p>
  <p>
    <strong>Market phase:</strong>
    <%= @stock.market_phase %>
  </p>
  <p>
    <strong>Corporate url:</strong>
    <%= @stock.corporate_url %>
  </p>
  <p>
    <strong>Address:</strong>
    <%= @stock.address %>
  </p>
  <p>
    <strong>Phone:</strong>
    <%= @stock.phone %>
  </p>
  <p>
    <strong>Market:</strong>
    <%= @stock.market %>
  </p>
  <p>
    <strong>Currency:</strong>
    <%= @stock.currency %>
  </p>
  <p>
    <strong>Profile:</strong>
    <%= @stock.profile %>
  </p>
  <p>
    <strong>Keywords:</strong>
    <%= @stock.keywords %>
  </p>
  <p>
    <strong>Dividend:</strong>
    <%= @stock.dividend %>
  </p>
  <p>
    <strong>Dividend date:</strong>
    <%= @stock.dividend_date %>
  </p>
  <p>
    <strong>Dividend yeld:</strong>
    <%= @stock.dividend_yeld %>
  </p>
  <p>
    <strong>Performance1:</strong>
    <%= @stock.performance1 %>
  </p>
  <p>
    <strong>Performance6:</strong>
    <%= @stock.performance6 %>
  </p>
  <p>
    <strong>Performance12:</strong>
    <%= @stock.performance12 %>
  </p>
  <p>
    <strong>Code:</strong>
    <%= @stock.code %>
  </p>
  <%= link_to 'Edit', edit_stock_path(@stock) %> |
  <%= link_to 'Back', stocks_path %>
</div>