tradingradar/config/routes.rb
Rails.application.routes.draw do
  get 'message/emailreset'
  root "home#index", as: "home"

  get "press_release/source0" #testing source
  get "press_release/source1"
  get "press_release/source2"
  get "press_release/source3"
  get "press_release/source4"
  get "press_release/source5"
  get "press_release/source6"
  get "press_release/source7"
  get "press_release/source8"
  get "press_release/source9"
  get "press_release/source10"
  get "press_release/source11"
  get "press_release/source12"
  get "press_release/source13"
  get "press_release/source14"
  get "press_release/source15"
  get "press_release/source16"
  get "press_release/source16"
  get "press_release/source17"
  get "press_release/source18"
  get "press_release/source19"

  #get 'stock/:id' => 'stock#press_release' #good for: http://www.localhost:3000/stock/a2a/
  get "stock/:id" => "stock#index"  # Goes to --> http://localhost:3000/stock/a2a/?isin=IT0001233417

  get "market/italy"
  get "market/italy" => "market#italy"

  get "market/france"
  get "market/france" => "market#france"

  get "pages/contacts"
  post "contacts" => "pages#contacts"
  get "contacts" => "pages#contacts"

  get "pages/about"
  get "about" => "pages#about"

  post "send" => "pages#send"

  get "search/search"
  get "search" => "search#search"

  #devise_for :followers

  get "home/index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "signup" => "users#new"

  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"

  scope "(:locale)" do
    resources :market_suggestions_newsletters
    resources :analyses
    resources :follow_stock_newsletters
    resources :items
    resources :dax30_reports
    resources :users
    resources :markets
    resources :user_reports
    resources :cac40_reports
    resources :fias_reports
    resources :sources
    resources :stocks
    resources :users
    resources :source_frances
    resources :source_italies
    root "home#index", as: "home-locale", via: :all

    get "pages/contacts"
    get "pages/about"
    get "pages/privacy-policy"
  end

  devise_for :followers, :controllers => {:omniauth_callbacks => "followers/omniauth_callbacks"}
end

tradingradar/app/models/follow_stock_newsletter.rb
class FollowStockNewsletter < ApplicationRecord
  validates :stock, presence: true
  #validates :isin, presence: true
  validates :privacy, presence: true
  validates :email, presence: true, format: {with: /\b[A-Z0-9._%a-z\-]+@(?:[A-Z0-9a-z\-]+\.)+[A-Za-z]{2,4}\z/, message: " format not recognized"}

  validates :email, uniqueness: {scope: :isin}
end

tradingradar/app/controllers/follow_stock_newsletters_controller.rb
class FollowStockNewslettersController < ApplicationController
  before_action :set_follow_stock_newsletter, only: [:show, :edit, :update, :destroy]

  # GET /follow_stock_newsletters
  # GET /follow_stock_newsletters.json
  def index
    @follow_stock_newsletters = FollowStockNewsletter.all
  end

  # GET /follow_stock_newsletters/1
  # GET /follow_stock_newsletters/1.json
  def show
  end

  # GET /follow_stock_newsletters/new
  def new
    @follow_stock_newsletter = FollowStockNewsletter.new
  end

  # GET /follow_stock_newsletters/1/edit
  def edit
  end

  # POST /follow_stock_newsletters
  # POST /follow_stock_newsletters.json
  def create
    @follow_stock_newsletter = FollowStockNewsletter.new(follow_stock_newsletter_params)
    @follow_stock_newsletter.code = Digest::SHA1.hexdigest([Time.now, rand].join)

    respond_to do |format|
      if @follow_stock_newsletter.save
        format.html { redirect_to @follow_stock_newsletter, notice: t("activerecord.confirm.models.follow_stock_newsletter.created") }
        format.js { flash.now[:notice] = t("activerecord.confirm.models.follow_stock_newsletter.created") }
        format.json { render :show, status: :created, location: @follow_stock_newsletter }
      else
        format.html { render :new }
        format.js { flash.now[:alert] = t("activerecord.errors.generic") }
      end
    end
  end

  # PATCH/PUT /follow_stock_newsletters/1
  # PATCH/PUT /follow_stock_newsletters/1.json
  def update
    respond_to do |format|
      if @follow_stock_newsletter.update(follow_stock_newsletter_params)
        format.html { redirect_to @follow_stock_newsletter, notice: "Follow stock newsletter was successfully updated." }
        format.json { render :show, status: :ok, location: @follow_stock_newsletter }
      else
        format.html { render :edit }
        format.json { render json: @follow_stock_newsletter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /follow_stock_newsletters/1
  # DELETE /follow_stock_newsletters/1.json
  def destroy
    @follow_stock_newsletter.destroy
    respond_to do |format|
      format.html { redirect_to follow_stock_newsletters_url, notice: "Follow stock newsletter was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_follow_stock_newsletter
    @follow_stock_newsletter = FollowStockNewsletter.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def follow_stock_newsletter_params
    params.require(:follow_stock_newsletter).permit(:stock, :isin, :email, :active, :privacy, :referrer, :sended, :total_sended, :code)
  end
end

tradingradar/app/helpers/follow_stock_newsletters_helper.rb
module FollowStockNewslettersHelper
end

tradingradar/app/views/follow_stock_newsletters/_alerts.erb
<% if @follow_stock_newsletter.errors.any? %>		
	<div class="alert alert-danger" role="alert">
		<ul><% @follow_stock_newsletter.errors.full_messages.each do |message| %><li><%= message %></li><% end %></ul>
		<div><%= alert %></div>
 	</div>
<% else %>  
  	<div class="notice alert alert-success" role="alert">
		<%= notice %>
	</div>
<% end %>
	

tradingradar/app/views/follow_stock_newsletters/_form.html.erb
<%= form_with(model: follow_stock_newsletter, local: true) do |form| %>
  <% if follow_stock_newsletter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(follow_stock_newsletter.errors.count, "error") %> prohibited this follow_stock_newsletter from being saved:</h2>

      <ul>
      <% follow_stock_newsletter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :stock %>
    <%= form.text_field :stock %>
  </div>

  <div class="field">
    <%= form.label :isin %>
    <%= form.text_field :isin %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :active %>
    <%= form.check_box :active %>
  </div>

  <div class="field">
    <%= form.label :privacy %>
    <%= form.check_box :privacy %>
  </div>

  <div class="field">
    <%= form.label :referrer %>
    <%= form.text_field :referrer %>
  </div>

  <div class="field">
    <%= form.label :sended %>
    <%= form.text_field :sended %>
  </div>

  <div class="field">
    <%= form.label :total_sended %>
    <%= form.text_field :total_sended %>
  </div>

  <div class="field">
    <%= form.label :code %>
    <%= form.text_field :code %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

tradingradar/app/views/follow_stock_newsletters/create.js.erb
//Create action from FollowStockNewslettersController
$('#follow_stock_newsletters_wrap .alert-wrapper').html("<%= j render("alerts") %>");
$('#follow_stock_newsletters_wrap_sidebar .alert-wrapper').html("<%= j render("alerts") %>");

tradingradar/app/views/follow_stock_newsletters/edit.html.erb
<%= render("./partials/header/header") %>
<!--The main content-->
<div class="shell">
  <h1>Editing Follow Stock Newsletter</h1>
  <%= render 'form', follow_stock_newsletter: @follow_stock_newsletter %>
  <%= link_to 'Show', @follow_stock_newsletter %> |
  <%= link_to 'Back', follow_stock_newsletters_path %>
</div>

tradingradar/app/views/follow_stock_newsletters/index.html.erb
<%= render("./partials/header/header") %>
<!--The main content-->
<div class="shell">
  <p id="notice"><%= notice %></p>
  <h1>Follow Stock Newsletters</h1>
  <table>
    <thead>
      <tr>
        <th>Stock</th>
        <th>Isin</th>
        <th>Email</th>
        <th>Active</th>
        <th>Privacy</th>
        <th>Referrer</th>
        <th>Sended</th>
        <th>Total sended</th>
        <th>Code</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @follow_stock_newsletters.each do |follow_stock_newsletter| %>
        <tr>
          <td><%= follow_stock_newsletter.stock %></td>
          <td><%= follow_stock_newsletter.isin %></td>
          <td><%= follow_stock_newsletter.email %></td>
          <td><%= follow_stock_newsletter.active %></td>
          <td><%= follow_stock_newsletter.privacy %></td>
          <td><%= follow_stock_newsletter.referrer %></td>
          <td><%= follow_stock_newsletter.sended %></td>
          <td><%= follow_stock_newsletter.total_sended %></td>
          <td><%= follow_stock_newsletter.code %></td>
          <td><%= link_to 'Show', follow_stock_newsletter %></td>
          <td><%= link_to 'Edit', edit_follow_stock_newsletter_path(follow_stock_newsletter) %></td>
          <td><%= link_to 'Destroy', follow_stock_newsletter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
  <%= link_to 'New Follow Stock Newsletter', new_follow_stock_newsletter_path %>
</div>

tradingradar/app/views/follow_stock_newsletters/new.html.erb
<%= render("./partials/header/header") %>
<!--The main content-->
<div class="shell">
  <h1>New Follow Stock Newsletter</h1>
  <%= render 'form', follow_stock_newsletter: @follow_stock_newsletter %>
  <%= link_to 'Back', follow_stock_newsletters_path %>
</div>

tradingradar/app/views/follow_stock_newsletters/show.html.erb
<%= render("./partials/header/header") %>
<!--The main content-->
<div class="shell">
  <p id="notice"><%= notice %></p>
  <p>
    <strong>Stock:</strong>
    <%= @follow_stock_newsletter.stock %>
  </p>
  <p>
    <strong>Isin:</strong>
    <%= @follow_stock_newsletter.isin %>
  </p>
  <p>
    <strong>Email:</strong>
    <%= @follow_stock_newsletter.email %>
  </p>
  <p>
    <strong>Active:</strong>
    <%= @follow_stock_newsletter.active %>
  </p>
  <p>
    <strong>Privacy:</strong>
    <%= @follow_stock_newsletter.privacy %>
  </p>
  <p>
    <strong>Referrer:</strong>
    <%= @follow_stock_newsletter.referrer %>
  </p>
  <p>
    <strong>Sended:</strong>
    <%= @follow_stock_newsletter.sended %>
  </p>
  <p>
    <strong>Total sended:</strong>
    <%= @follow_stock_newsletter.total_sended %>
  </p>
  <p>
    <strong>Code:</strong>
    <%= @follow_stock_newsletter.code %>
  </p>
  <%= link_to 'Edit', edit_follow_stock_newsletter_path(@follow_stock_newsletter) %> |
  <%= link_to 'Back', follow_stock_newsletters_path %>
</div>